import type { RiskCategorySummary, SessionEvent, VerificationRun } from "../types/index.js";

export type ReplayTimelineItem = Pick<
  SessionEvent,
  "type" | "timestamp" | "title" | "message" | "metadata"
>;

export interface HtmlReplayInput {
  task: string;
  sessionId: string;
  startedAt: string;
  timeline: ReplayTimelineItem[];
  changedFiles: string[];
  changedFileGroups?: RiskCategorySummary[] | undefined;
  riskBadges: string[];
  verificationEvidence: VerificationRun[];
  reviewReadiness?: string | undefined;
  recommendation: string;
}

export function renderHtmlReplay(input: HtmlReplayInput): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AgentFlight Replay ${escapeHtml(input.sessionId)}</title>
  <style>
    :root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    body { margin: 0; background: #f7f8fa; color: #1b1f24; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 24px; }
    header { border-bottom: 1px solid #d8dee4; padding-bottom: 24px; margin-bottom: 28px; }
    h1 { font-size: 32px; line-height: 1.1; margin: 0 0 12px; letter-spacing: 0; }
    h2 { font-size: 18px; margin: 28px 0 12px; }
    .meta { color: #57606a; font-size: 14px; }
    .badges { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 16px; }
    .badge { border: 1px solid #d0d7de; border-radius: 999px; padding: 4px 10px; background: #ffffff; font-size: 13px; }
    .summary-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; margin: 0 0 28px; }
    .summary-card { background: #ffffff; border: 1px solid #d0d7de; border-radius: 8px; padding: 14px; min-width: 0; }
    .summary-card span { color: #57606a; display: block; font-size: 12px; font-weight: 600; text-transform: uppercase; }
    .summary-card strong { display: block; font-size: 18px; margin-top: 4px; overflow-wrap: anywhere; }
    .panel { background: #ffffff; border: 1px solid #d0d7de; border-radius: 8px; padding: 18px; margin: 16px 0; }
    .timeline { border-left: 3px solid #d0d7de; padding-left: 16px; }
    .timeline-item { margin: 0 0 14px; }
    .timeline-item strong { display: block; }
    .verification-grid { display: grid; gap: 12px; }
    .verification-card { border: 1px solid #d0d7de; border-radius: 8px; padding: 14px; background: #fbfcfe; }
    .verification-card.passed { border-color: #2da44e; }
    .verification-card.failed { border-color: #cf222e; }
    .verification-card strong { display: inline-block; margin-bottom: 6px; }
    footer { color: #57606a; font-size: 13px; margin-top: 28px; }
    ul { margin: 0; padding-left: 22px; }
    li { margin: 6px 0; }
    code { background: #f0f3f6; border-radius: 4px; padding: 2px 5px; }
    @media (max-width: 760px) { .summary-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }
  </style>
</head>
<body>
  <main>
    <header>
      <div class="meta">AgentFlight replay · ${escapeHtml(input.sessionId)}</div>
      <h1>${escapeHtml(input.task)}</h1>
      <div class="meta">Started ${escapeHtml(input.startedAt)}</div>
      <div class="badges">${input.riskBadges.map((badge) => `<span class="badge">${escapeHtml(badge)}</span>`).join("")}</div>
    </header>

    ${renderSummary(input)}

    <section class="panel">
      <h2>Timeline</h2>
      ${renderTimeline(input.timeline)}
    </section>

    <section class="panel">
      <h2>Changed File Groups</h2>
      ${renderFileGroups(input.changedFileGroups ?? [])}
      <h2>Changed Files</h2>
      ${renderFileList(input.changedFiles)}
    </section>

    <section class="panel">
      <h2>Verification Evidence</h2>
      ${renderVerification(input.verificationEvidence)}
    </section>

    <section class="panel">
      <h2>Recommendation</h2>
      <p>${escapeHtml(input.recommendation)}</p>
    </section>

    <footer>Generated by AgentFlight</footer>
  </main>
</body>
</html>
`;
}

function renderSummary(input: HtmlReplayInput): string {
  const passed = input.verificationEvidence.filter((item) => item.status === "passed").length;
  const failed = input.verificationEvidence.filter((item) => item.status === "failed").length;
  const risk = input.riskBadges[0] ?? "unknown";
  const readiness = input.reviewReadiness ?? "Unknown";

  return `<section class="summary-grid" aria-label="Session summary">
      ${renderSummaryCard("Risk", risk)}
      ${renderSummaryCard("Changed Files", String(input.changedFiles.length))}
      ${renderSummaryCard("Proof", `${passed} passed / ${failed} failed`)}
      ${renderSummaryCard("Readiness", readiness)}
    </section>`;
}

function renderSummaryCard(label: string, value: string): string {
  return `<div class="summary-card"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`;
}

function renderTimeline(items: ReplayTimelineItem[]): string {
  if (items.length === 0) return "<p>No timeline events recorded.</p>";
  return `<div class="timeline">${items
    .map(
      (item) => `<div class="timeline-item">
        <strong>${escapeHtml(item.title)}</strong>
        <div class="meta">${escapeHtml(item.timestamp)} · ${escapeHtml(item.type)}</div>
        ${item.message ? `<div>${escapeHtml(item.message)}</div>` : ""}
      </div>`
    )
    .join("")}</div>`;
}

function renderFileGroups(groups: RiskCategorySummary[]): string {
  if (groups.length === 0) return "<p>No changed file groups detected.</p>";
  return `<ul>${groups
    .map(
      (group) =>
        `<li><strong>${escapeHtml(group.category)}</strong>: ${group.files.map((file) => `<code>${escapeHtml(file)}</code>`).join(", ")}</li>`
    )
    .join("")}</ul>`;
}

function renderFileList(files: string[]): string {
  if (files.length === 0) return "<p>No changed files detected.</p>";
  return `<ul>${files.map((file) => `<li><code>${escapeHtml(file)}</code></li>`).join("")}</ul>`;
}

function renderVerification(evidence: VerificationRun[]): string {
  if (evidence.length === 0) return "<p>No verification evidence recorded.</p>";
  return `<div class="verification-grid">${evidence
    .map(
      (item) => `<div class="verification-card ${escapeHtml(item.status)}">
        <strong>${escapeHtml(item.status)}</strong>
        <div><code>${escapeHtml(item.command)}</code></div>
        <div class="meta">Exit ${escapeHtml(String(item.exitCode ?? "unknown"))} · ${escapeHtml(String(item.durationMs))}ms</div>
        <div class="meta">stdout: ${escapeHtml(item.stdoutPath)}</div>
        <div class="meta">stderr: ${escapeHtml(item.stderrPath)}</div>
      </div>`
    )
    .join("")}</div>`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}
