import {
  compactCommandInText,
  collectSuggestedCommandsForDisplay,
  escapeMarkdownBlockForDisplay,
  escapeMarkdownTextForDisplay,
  escapeHtmlForDisplay,
  formatCommandForDisplay,
  formatFileListForDisplay,
  formatProjectRequirementDetailsForDisplay,
  formatProjectRequirementStatusForDisplay,
  formatProofCalibrationDetailsForDisplay,
  formatProofCalibrationStatusForDisplay,
  formatProofCalibrationSummaryForDisplay,
  formatProofFreshnessAttributionForDisplay,
  formatProofStatusForDisplay,
  formatReviewReceiptForDisplay,
  formatReviewQueueForDisplay,
  formatReviewRoutesForDisplay,
  formatReviewContractProofReferencesForDisplay,
  formatReviewContractReviewPathForDisplay,
  formatReviewContractStatusForDisplay,
  formatTrustDeltaForDisplay,
  formatToolForReport,
  formatVerificationCountLine,
  formatVerificationFailureContext,
  formatVerifyCommandForDisplay
} from "../core/output.js";
import { formatBaseframeResultForMarkdown } from "../core/baseframe.js";
import type { VerificationFailureCounts } from "../core/output.js";
import type {
  AgentFlightResultV1,
  ProjectReviewContractEvaluation,
  ProjectReviewRequirementStatus,
  ProofCalibration,
  ProofCalibrationSuggestion,
  ReviewIntelligence,
  RiskAnalysis,
  SessionEvent,
  ToolAdapterResult,
  VerificationRun
} from "../types/index.js";

export interface MarkdownReportInput {
  task: string;
  sessionId: string;
  startedAt: string;
  changedFiles: string[];
  timelineEvents?: SessionEvent[] | undefined;
  risk: RiskAnalysis;
  verificationCommands: string[];
  verificationEvidence: VerificationRun[];
  verificationSummary?: VerificationFailureCounts | undefined;
  verificationGaps?: string[] | undefined;
  recommendation?: string | undefined;
  nextAction?: string | undefined;
  review?: ReviewIntelligence | undefined;
  baseframeResult?: AgentFlightResultV1 | undefined;
  tooling: {
    projscan: ToolAdapterResult;
    agentloopkit: ToolAdapterResult;
  };
}

export type MarkdownReportMode = "full" | "compact" | "pr-comment";

export interface MarkdownReportOptions {
  mode?: MarkdownReportMode | undefined;
}

export function renderMarkdownReport(
  input: MarkdownReportInput,
  options: MarkdownReportOptions = {}
): string {
  if (options.mode === "compact") return renderCompactMarkdownReport(input);
  if (options.mode === "pr-comment") return renderPrCommentDraft(input);

  return `# AgentFlight Proof Report

## Task
${escapeMarkdownTextForDisplay(input.task)}

## Session
- Session ID: ${escapeMarkdownTextForDisplay(input.sessionId)}
- Started: ${escapeMarkdownTextForDisplay(input.startedAt)}

## Changed Files
${renderChangedFileList(input.changedFiles)}

## Risk Summary
- Level: ${input.risk.level}
- Changed files: ${input.risk.changedFiles}
${renderList(input.risk.reasons)}

${renderBaseframeIntegration(input)}

## Verification Evidence
${renderVerification(input)}

## Review First
${renderReviewFirst(input)}

## Trust Delta
${renderTrustDelta(input)}

## Review Queue
${renderReviewQueue(input)}

## Review Routing
${renderReviewRouting(input)}

${renderFullSuggestedCommands(input)}

## Review Receipt
${renderReviewReceipt(input)}

## Required Proof
${renderRequiredProof(input)}

${renderProofFreshnessSection(input)}

## Repo Calibration
${renderRepoCalibration(input.review?.calibration)}

## Review Contract
${renderReviewContract(input)}

## Proof Gaps
${renderProofGaps(input)}

## Review Readiness
${renderReviewReadiness(input)}

## Recommendation
${renderRecommendation(input)}

## Next Action
${renderNextAction(input)}

## Timeline
${renderTimeline(input.timelineEvents ?? [])}

## Tooling
- ProjScan: ${md(formatToolForReport("ProjScan", input.tooling.projscan))}
- AgentLoopKit: ${md(formatToolForReport("AgentLoopKit", input.tooling.agentloopkit))}

Generated by AgentFlight, powered by ProjScan and AgentLoopKit where available.
`;
}

function renderPrCommentDraft(input: MarkdownReportInput): string {
  return `## AgentFlight Review Summary

Generated locally by AgentFlight. Not posted automatically.

- Task: ${escapeMarkdownTextForDisplay(input.task)}
- Readiness: ${md(input.review?.readiness.label ?? input.recommendation ?? "Unknown")}
- Risk: ${input.risk.level}
- Changed files: ${input.changedFiles.length}

${renderBaseframeIntegration(input).replaceAll("## ", "### ")}

### Review first
${renderReviewFirst(input)}

### Trust delta
${renderTrustDelta(input)}

### Review queue
${renderReviewQueue(input)}

### Review routing
${renderReviewRouting(input)}

${renderFullSuggestedCommands(input, "###")}

### Required proof
${renderRequiredProof(input)}

${renderProofFreshnessSection(input, "###")}

### Repo calibration
${renderRepoCalibration(input.review?.calibration)}

### Proof gaps:
${renderPrCommentProofGaps(input)}

### Verification evidence
${renderVerification(input)}

### Review receipt
${renderReviewReceipt(input)}

### Next action
${renderNextAction(input)}
`;
}

function renderCompactMarkdownReport(input: MarkdownReportInput): string {
  return `# AgentFlight Compact Report

## Summary
- Task: ${escapeMarkdownTextForDisplay(input.task)}
- Session ID: ${escapeMarkdownTextForDisplay(input.sessionId)}
- Started: ${escapeMarkdownTextForDisplay(input.startedAt)}
- Changed files: ${input.changedFiles.length}
- Risk: ${input.risk.level}

${renderBaseframeIntegration(input)}

## Review Readiness
${renderReviewReadiness(input)}

## Review First
${renderReviewFirst(input)}

## Trust Delta
${renderTrustDelta(input)}

## Review Queue
${renderReviewQueue(input)}

## Review Routing
${renderReviewRouting(input)}

${renderFullSuggestedCommands(input)}

## Review Receipt
${renderReviewReceipt(input)}

## Required Proof
${renderRequiredProof(input)}

${renderProofFreshnessSection(input)}

## Repo Calibration
${renderRepoCalibration(input.review?.calibration)}

## Review Contract
${renderReviewContract(input)}

## Proof Gaps
${renderProofGaps(input)}

## Verification Evidence
${renderVerification(input)}

## Recommendation
${renderRecommendation(input)}

## Next Action
${renderNextAction(input)}

Generated by AgentFlight.
`;
}

function renderList(items: string[], empty = "None."): string {
  return items.length
    ? items.map((item) => `- ${escapeMarkdownTextForDisplay(item)}`).join("\n")
    : empty;
}

function renderBaseframeIntegration(input: MarkdownReportInput): string {
  return input.baseframeResult ? formatBaseframeResultForMarkdown(input.baseframeResult) : "";
}

function renderChangedFileList(files: string[]): string {
  if (files.length === 0) return "No changed files detected.";
  const visibleFiles = files.slice(0, 80);
  const rows = visibleFiles.map((file) => `- ${escapeMarkdownTextForDisplay(file)}`);
  const remaining = files.length - visibleFiles.length;
  if (remaining > 0) rows.push(`- ${remaining} more changed files in replay/status JSON.`);
  return rows.join("\n");
}

function renderVerification(input: MarkdownReportInput): string {
  if (input.verificationEvidence.length === 0) {
    const commands = input.verificationCommands.length
      ? `\n\nSuggested commands:\n${renderList(input.verificationCommands)}`
      : "";
    const gaps =
      !input.review && input.verificationGaps?.length
        ? `\n\nGaps:\n${renderList(input.verificationGaps)}`
        : "";
    return `No verification evidence recorded.${gaps}${commands}`;
  }

  const evidence = input.verificationEvidence
    .map((run) => {
      const command = markdownText(formatCommandForDisplay(run.command));
      const base = `- ${command}: ${md(run.status)} (exit ${run.exitCode ?? "unknown"}, ${run.durationMs}ms)\n  - stdout: ${md(run.stdoutPath)}\n  - stderr: ${md(run.stderrPath)}`;
      if (run.status === "failed" && run.outputExcerpt) {
        return `${base}\n  - Output excerpt:\n\n${renderExcerptFence(run.outputExcerpt)}`;
      }
      return base;
    })
    .join("\n");
  const summary = input.verificationSummary ?? summarizeVerificationEvidence(input);
  const failureContext = formatVerificationFailureContext(summary);
  const summaryText = `${formatVerificationCountLine(summary)}${failureContext ? `\n${failureContext}` : ""}`;
  const gaps =
    !input.review && input.verificationGaps?.length
      ? `\n\nGaps:\n${renderList(input.verificationGaps)}`
      : "";

  return `${summaryText}\n${evidence}${gaps}`;
}

function summarizeVerificationEvidence(input: MarkdownReportInput): VerificationFailureCounts {
  const passed = input.verificationEvidence.filter((run) => run.status === "passed").length;
  const failed = input.verificationEvidence.filter((run) => run.status === "failed").length;
  return {
    passed,
    failed,
    unresolvedFailed: failed,
    resolvedFailed: 0
  };
}

function renderExcerptFence(excerpt: string): string {
  const longestBacktickRun = Math.max(
    2,
    ...Array.from(excerpt.matchAll(/`+/g), (match) => match[0].length)
  );
  const fence = "`".repeat(longestBacktickRun + 1);
  return `${fence}text\n${excerpt}\n${fence}`;
}

function renderTimeline(events: SessionEvent[]): string {
  if (events.length === 0) return "No timeline events recorded.";
  return events
    .map((event) => {
      const message = event.message ? ` - ${md(event.message)}` : "";
      return `- ${md(event.timestamp)}: ${md(event.title)}${message}`;
    })
    .join("\n");
}

function renderReviewFirst(input: MarkdownReportInput): string {
  const focus = input.review?.focus;
  if (focus && focus.length > 0) {
    return focus
      .map(
        (item) =>
          `${item.rank}. ${escapeMarkdownTextForDisplay(item.file)}\n   - Proof: ${md(formatProofStatusForDisplay(item.proofStatus))}\n   - Why: ${escapeMarkdownTextForDisplay(item.reasons.join("; "))}\n   - Focus: ${escapeMarkdownTextForDisplay(item.suggestedReviewerFocus)}${item.suggestedCommand ? `\n   - Suggested proof: ${markdownText(formatVerifyCommandForDisplay(item.suggestedCommand))}` : ""}`
      )
      .join("\n");
  }

  return input.risk.categories.length
    ? input.risk.categories
        .map((summary) => `- ${md(summary.category)}: ${md(summary.files.join(", "))}`)
        .join("\n")
    : "- Confirm the session has meaningful changes before review.";
}

function renderRequiredProof(input: MarkdownReportInput): string {
  return renderProjectReviewContract(input.review?.projectReviewContract);
}

function renderProjectReviewContract(
  contract: ProjectReviewContractEvaluation | undefined
): string {
  if (!contract) return "- No project review contract configured.";
  if (!contract.enabled) return "- Project review contract disabled.";
  if (contract.requirements.length === 0) {
    return "- No project review contract requirements matched these changes.";
  }
  return contract.requirements.map(renderProjectRequirement).join("\n");
}

function renderProjectRequirement(requirement: ProjectReviewRequirementStatus): string {
  const details = formatProjectRequirementDetailsForDisplay(requirement)
    .map((line) => `\n  - ${md(line)}`)
    .join("");
  return `- ${md(formatProjectRequirementStatusForDisplay(requirement.status))} - ${md(requirement.label)}${details}`;
}

function renderRepoCalibration(calibration: ProofCalibration | undefined): string {
  if (!calibration) return "- No repo calibration history loaded.";
  if (calibration.suggestions.length === 0) {
    return `- ${md(formatProofCalibrationSummaryForDisplay(calibration))}`;
  }
  return [
    `- ${md(formatProofCalibrationSummaryForDisplay(calibration))}`,
    ...calibration.suggestions.map(renderRepoCalibrationSuggestion)
  ].join("\n");
}

function renderRepoCalibrationSuggestion(suggestion: ProofCalibrationSuggestion): string {
  const details = formatProofCalibrationDetailsForDisplay(suggestion)
    .map((line) => `\n  - ${md(line)}`)
    .join("");
  return `- ${md(formatProofCalibrationStatusForDisplay(suggestion.status))} - ${md(suggestion.category)}${details}`;
}

function renderProofFreshnessSection(input: MarkdownReportInput, heading = "##"): string {
  const lines = formatProofFreshnessAttributionForDisplay(input.review?.proofFreshness);
  if (lines.length === 0) return "";
  return `${heading} Proof Freshness\n${lines.map((line) => `- ${md(line)}`).join("\n")}`;
}

function renderTrustDelta(input: MarkdownReportInput): string {
  return md(formatTrustDeltaForDisplay(input.review?.trustDelta));
}

function renderReviewQueue(input: MarkdownReportInput): string {
  return md(formatReviewQueueForDisplay(input.review?.reviewQueue));
}

function renderReviewRouting(input: MarkdownReportInput): string {
  return md(formatReviewRoutesForDisplay(input.review?.reviewRoutes));
}

function renderReviewReceipt(input: MarkdownReportInput): string {
  return md(formatReviewReceiptForDisplay(input.review?.reviewReceipt));
}

function renderFullSuggestedCommands(input: MarkdownReportInput, heading = "##"): string {
  const commands = collectCompactSuggestedCommands(input.review);
  if (commands.length === 0) return "";
  return `${heading} Full Suggested Commands\n${commands.map(renderFullSuggestedCommand).join("\n")}`;
}

function collectCompactSuggestedCommands(review: ReviewIntelligence | undefined): string[] {
  return [...new Set(collectSuggestedCommandsForDisplay(review))].filter(isCompactCommand);
}

function isCompactCommand(command: string): boolean {
  return formatCommandForDisplay(command) !== command.trim().replace(/\s+/g, " ");
}

function renderFullSuggestedCommand(command: string): string {
  return `<details>
<summary>${escapeHtmlForDisplay(formatVerifyCommandForDisplay(command))}</summary>

${renderCommandFence(`agentflight verify -- ${command}`)}
</details>`;
}

function renderCommandFence(command: string): string {
  const longestBacktickRun = Math.max(
    2,
    ...Array.from(command.matchAll(/`+/g), (match) => match[0].length)
  );
  const fence = "`".repeat(longestBacktickRun + 1);
  return `${fence}bash\n${command}\n${fence}`;
}

function renderProofGaps(input: MarkdownReportInput): string {
  if (input.review) {
    return input.review.proofGaps.length
      ? input.review.proofGaps
          .map(
            (gap) =>
              `- ${md(gap.severity)}: ${md(compactCommandInText(gap.message, gap.suggestedCommand))}${gap.suggestedCommand ? `\n  - Suggested proof: ${markdownText(formatVerifyCommandForDisplay(gap.suggestedCommand))}` : ""}`
          )
          .join("\n")
      : "- none";
  }

  return input.verificationGaps?.length ? renderList(input.verificationGaps) : "- none";
}

function renderReviewContract(input: MarkdownReportInput): string {
  const contract = input.review?.contract;
  if (!contract || contract.claims.length === 0) return "- No review contract claims recorded.";

  const reviewPath = md(formatReviewContractReviewPathForDisplay(contract));
  const claims = contract.claims
    .map((claim) => {
      const files = claim.files.length
        ? `\n  - Files: ${md(formatFileListForDisplay(claim.files))}`
        : "";
      const evidence = claim.evidence.length
        ? `\n  - Evidence: ${md(claim.evidence.join("; "))}`
        : "";
      const proofReferences = md(formatReviewContractProofReferencesForDisplay(claim));
      const proofReferenceLine = proofReferences ? `\n  - ${proofReferences}` : "";
      const command = claim.suggestedCommand
        ? `\n  - Suggested proof: ${markdownText(formatVerifyCommandForDisplay(claim.suggestedCommand))}`
        : "";
      return `- ${md(formatReviewContractStatusForDisplay(claim.status))} - ${escapeMarkdownTextForDisplay(claim.text)}${files}${evidence}${proofReferenceLine}${command}`;
    })
    .join("\n");
  return [reviewPath, claims].filter(Boolean).join("\n\n");
}

function renderPrCommentProofGaps(input: MarkdownReportInput): string {
  const gaps = input.review?.proofGaps ?? [];
  if (gaps.length === 0 && !input.verificationGaps?.length) return "Proof gaps: none";
  return renderProofGaps(input);
}

function renderReviewReadiness(input: MarkdownReportInput): string {
  if (!input.review) return md(input.recommendation ?? "Unknown");
  const command = input.review.readiness.suggestedCommand;
  return `${md(input.review.readiness.label)}

Reason: ${md(compactCommandInText(input.review.readiness.reason, command))}
Next action: ${md(compactCommandInText(input.review.readiness.nextAction, command))}`;
}

function renderRecommendation(input: MarkdownReportInput): string {
  if (input.recommendation) {
    return `${md(input.recommendation)}.`;
  }
  if (input.verificationEvidence.length === 0) {
    return "Do not claim completion yet. Run the suggested verification commands and regenerate the report.";
  }
  if (input.risk.level === "high") {
    return "Request careful human review focused on the high-risk file categories before merging.";
  }
  return "Review the changed files and verification evidence before handoff.";
}

function renderNextAction(input: MarkdownReportInput): string {
  if (input.nextAction) {
    return md(compactCommandInText(input.nextAction, input.review?.readiness.suggestedCommand));
  }
  if (input.verificationEvidence.length === 0 && input.verificationCommands.length > 0) {
    return `Run ${md(input.verificationCommands[0]!)} and capture the result.`;
  }
  return "Prepare a scoped handoff for the next agent or reviewer.";
}

function md(value: string): string {
  return escapeMarkdownBlockForDisplay(value);
}

function markdownText(value: string): string {
  return escapeMarkdownBlockForDisplay(value);
}
