import type { RiskAnalysis, ToolAdapterResult, VerificationEvidence } from "../types/index.js";

export interface MarkdownReportInput {
  task: string;
  sessionId: string;
  startedAt: string;
  changedFiles: string[];
  risk: RiskAnalysis;
  verificationCommands: string[];
  verificationEvidence: VerificationEvidence[];
  tooling: {
    projscan: ToolAdapterResult;
    agentloopkit: ToolAdapterResult;
  };
}

export function renderMarkdownReport(input: MarkdownReportInput): string {
  return `# AgentFlight Proof Report

## Task
${input.task}

## Session
- Session ID: ${input.sessionId}
- Started: ${input.startedAt}

## Changed Files
${renderList(input.changedFiles, "No changed files detected.")}

## Risk Summary
- Level: ${input.risk.level}
- Changed files: ${input.risk.changedFiles}
${renderList(input.risk.reasons)}

## Verification Evidence
${renderVerification(input)}

## Review Focus
${renderReviewFocus(input.risk)}

## Recommendation
${renderRecommendation(input.risk, input.verificationEvidence)}

## Next Action
${renderNextAction(input)}

## Tooling
- ProjScan: ${formatTool(input.tooling.projscan)}
- AgentLoopKit: ${formatTool(input.tooling.agentloopkit)}

Generated by AgentFlight, powered by ProjScan and AgentLoopKit where available.
`;
}

function renderList(items: string[], empty = "None."): string {
  return items.length ? items.map((item) => `- ${item}`).join("\n") : empty;
}

function renderVerification(input: MarkdownReportInput): string {
  if (input.verificationEvidence.length === 0) {
    const commands = input.verificationCommands.length
      ? `\n\nSuggested commands:\n${renderList(input.verificationCommands)}`
      : "";
    return `No verification evidence recorded.${commands}`;
  }

  return input.verificationEvidence
    .map((evidence) => `- ${evidence.command}: ${evidence.status}`)
    .join("\n");
}

function renderReviewFocus(risk: RiskAnalysis): string {
  return risk.categories.length
    ? risk.categories
        .map((summary) => `- ${summary.category}: ${summary.files.join(", ")}`)
        .join("\n")
    : "- Confirm the session has meaningful changes before review.";
}

function renderRecommendation(risk: RiskAnalysis, evidence: VerificationEvidence[]): string {
  if (evidence.length === 0) {
    return "Do not claim completion yet. Run the suggested verification commands and regenerate the report.";
  }
  if (risk.level === "high") {
    return "Request careful human review focused on the high-risk file categories before merging.";
  }
  return "Review the changed files and verification evidence before handoff.";
}

function renderNextAction(input: MarkdownReportInput): string {
  if (input.verificationEvidence.length === 0 && input.verificationCommands.length > 0) {
    return `Run ${input.verificationCommands[0]} and capture the result.`;
  }
  return "Prepare a scoped handoff for the next agent or reviewer.";
}

function formatTool(result: ToolAdapterResult): string {
  const status = result.available ? "available" : "unavailable";
  const version = result.version ? ` ${result.version}` : "";
  const warnings = result.warnings.length ? ` (${result.warnings.join("; ")})` : "";
  return `${status}${version}${warnings}`;
}
