import type {
  RiskAnalysis,
  SessionEvent,
  ToolAdapterResult,
  VerificationRun
} from "../types/index.js";
import type { ReviewReadiness } from "../core/verification.js";

export interface MarkdownReportInput {
  task: string;
  sessionId: string;
  startedAt: string;
  changedFiles: string[];
  timelineEvents?: SessionEvent[] | undefined;
  risk: RiskAnalysis;
  verificationCommands: string[];
  verificationEvidence: VerificationRun[];
  verificationGaps?: string[] | undefined;
  recommendation?: ReviewReadiness | undefined;
  nextAction?: string | undefined;
  tooling: {
    projscan: ToolAdapterResult;
    agentloopkit: ToolAdapterResult;
  };
}

export function renderMarkdownReport(input: MarkdownReportInput): string {
  return `# AgentFlight Proof Report

## Task
${input.task}

## Session
- Session ID: ${input.sessionId}
- Started: ${input.startedAt}

## Timeline
${renderTimeline(input.timelineEvents ?? [])}

## Changed Files
${renderList(input.changedFiles, "No changed files detected.")}

## Risk Summary
- Level: ${input.risk.level}
- Changed files: ${input.risk.changedFiles}
${renderList(input.risk.reasons)}

## Verification Evidence
${renderVerification(input)}

## Review Focus
${renderReviewFocus(input.risk)}

## Recommendation
${renderRecommendation(input)}

## Next Action
${renderNextAction(input)}

## Tooling
- ProjScan: ${formatTool(input.tooling.projscan)}
- AgentLoopKit: ${formatTool(input.tooling.agentloopkit)}

Generated by AgentFlight, powered by ProjScan and AgentLoopKit where available.
`;
}

function renderList(items: string[], empty = "None."): string {
  return items.length ? items.map((item) => `- ${item}`).join("\n") : empty;
}

function renderVerification(input: MarkdownReportInput): string {
  if (input.verificationEvidence.length === 0) {
    const commands = input.verificationCommands.length
      ? `\n\nSuggested commands:\n${renderList(input.verificationCommands)}`
      : "";
    const gaps = input.verificationGaps?.length
      ? `\n\nGaps:\n${renderList(input.verificationGaps)}`
      : "";
    return `No verification evidence recorded.${gaps}${commands}`;
  }

  const evidence = input.verificationEvidence
    .map(
      (run) =>
        `- ${run.command}: ${run.status} (exit ${run.exitCode ?? "unknown"}, ${run.durationMs}ms)\n  - stdout: ${run.stdoutPath}\n  - stderr: ${run.stderrPath}`
    )
    .join("\n");
  const gaps = input.verificationGaps?.length
    ? `\n\nGaps:\n${renderList(input.verificationGaps)}`
    : "";

  return `${evidence}${gaps}`;
}

function renderTimeline(events: SessionEvent[]): string {
  if (events.length === 0) return "No timeline events recorded.";
  return events
    .map((event) => {
      const message = event.message ? ` - ${event.message}` : "";
      return `- ${event.timestamp}: ${event.title}${message}`;
    })
    .join("\n");
}

function renderReviewFocus(risk: RiskAnalysis): string {
  return risk.categories.length
    ? risk.categories
        .map((summary) => `- ${summary.category}: ${summary.files.join(", ")}`)
        .join("\n")
    : "- Confirm the session has meaningful changes before review.";
}

function renderRecommendation(input: MarkdownReportInput): string {
  if (input.recommendation) {
    return `${input.recommendation}.`;
  }
  if (input.verificationEvidence.length === 0) {
    return "Do not claim completion yet. Run the suggested verification commands and regenerate the report.";
  }
  if (input.risk.level === "high") {
    return "Request careful human review focused on the high-risk file categories before merging.";
  }
  return "Review the changed files and verification evidence before handoff.";
}

function renderNextAction(input: MarkdownReportInput): string {
  if (input.nextAction) return input.nextAction;
  if (input.verificationEvidence.length === 0 && input.verificationCommands.length > 0) {
    return `Run ${input.verificationCommands[0]} and capture the result.`;
  }
  return "Prepare a scoped handoff for the next agent or reviewer.";
}

function formatTool(result: ToolAdapterResult): string {
  const status = result.available ? "available" : "unavailable";
  const version = result.version ? ` ${result.version}` : "";
  const warnings = result.warnings.length ? ` (${result.warnings.join("; ")})` : "";
  return `${status}${version}${warnings}`;
}
