import { describe, expect, it } from "vitest";
import { renderMarkdownReport } from "../../src/renderers/markdown-report.js";

describe("markdown proof report", () => {
  it("renders required sections without claiming missing proof passed", () => {
    const markdown = renderMarkdownReport({
      task: "Add password reset flow",
      sessionId: "af-1",
      startedAt: "2026-06-13T12:00:00.000Z",
      changedFiles: ["src/auth/reset.ts"],
      risk: {
        level: "high",
        changedFiles: 1,
        categories: [{ category: "auth", files: ["src/auth/reset.ts"] }],
        reasons: ["Authentication-sensitive files changed."]
      },
      verificationCommands: ["npm test"],
      verificationEvidence: [],
      timelineEvents: [],
      review: {
        focus: [
          {
            rank: 1,
            file: "src/auth/reset.ts",
            category: "auth",
            riskLevel: "high",
            score: 130,
            reasons: ["identity/session path", "no passing test evidence"],
            suggestedReviewerFocus: "Check session, permission, and identity boundaries first.",
            proofStatus: "missing",
            suggestedCommand: "npm test",
            relatedProofGapIds: ["missing-auth-test-proof"]
          }
        ],
        proofGaps: [
          {
            id: "missing-auth-test-proof",
            severity: "blocking",
            message:
              "Sensitive auth, payment, or security files changed without passing test evidence.",
            suggestedCommand: "npm test",
            relatedFiles: ["src/auth/reset.ts"]
          }
        ],
        readiness: {
          state: "needs_verification",
          label: "Needs verification",
          reason:
            "Sensitive auth, payment, or security files changed without passing test evidence.",
          nextAction: "Run agentflight verify -- npm test",
          suggestedCommand: "npm test",
          proofGaps: []
        }
      },
      tooling: {
        projscan: { available: false, warnings: ["ProjScan unavailable"] },
        agentloopkit: { available: true, warnings: [] }
      }
    });

    expect(markdown).toContain("# AgentFlight Proof Report");
    expect(markdown).toContain("## Timeline");
    expect(markdown).toContain("No timeline events recorded.");
    expect(markdown).toContain("## Verification Evidence");
    expect(markdown).toContain("No verification evidence recorded.");
    expect(markdown).toContain("## Review First");
    expect(markdown).toContain("src/auth/reset.ts");
    expect(markdown).toContain("identity/session path");
    expect(markdown).toContain("## Proof Gaps");
    expect(markdown).toContain("Sensitive auth, payment, or security files changed");
    expect(markdown).toContain("## Review Readiness");
    expect(markdown).toContain("Needs verification");
    expect(markdown).not.toContain("tests passed");
    expect(markdown).toContain("Generated by AgentFlight");
  });

  it("compacts long suggested proof commands in dense report sections", () => {
    const longCommand = `node -e "${"console.error('very noisy proof command'); ".repeat(12)}process.exit(1)"`;
    const markdown = renderMarkdownReport({
      task: "Dogfood failure",
      sessionId: "af-long-command",
      startedAt: "2026-06-17T12:00:00.000Z",
      changedFiles: ["src/auth/reset.ts"],
      risk: {
        level: "high",
        changedFiles: 1,
        categories: [{ category: "auth", files: ["src/auth/reset.ts"] }],
        reasons: ["Authentication-sensitive files changed."]
      },
      verificationCommands: [],
      verificationEvidence: [],
      timelineEvents: [],
      review: {
        focus: [
          {
            rank: 1,
            file: "src/auth/reset.ts",
            category: "auth",
            riskLevel: "high",
            score: 130,
            reasons: ["identity/session path", "matching proof missing"],
            suggestedReviewerFocus: "Check session, permission, and identity boundaries first.",
            proofStatus: "missing",
            suggestedCommand: longCommand,
            relatedProofGapIds: ["failed-verification"]
          }
        ],
        proofGaps: [
          {
            id: "failed-verification",
            severity: "blocking",
            message: `A verification command failed and must be fixed or rerun successfully: ${longCommand}`,
            suggestedCommand: longCommand,
            relatedFiles: ["src/auth/reset.ts"]
          }
        ],
        readiness: {
          state: "blocked_by_failed_verification",
          label: "Blocked by failed verification",
          reason: `A verification command failed and must be fixed or rerun successfully: ${longCommand}`,
          nextAction: `Fix the failed command, then rerun agentflight verify -- ${longCommand}`,
          suggestedCommand: longCommand,
          proofGaps: []
        }
      },
      tooling: {
        projscan: { available: true, warnings: [] },
        agentloopkit: { available: true, warnings: [] }
      }
    });

    expect(markdown).toContain("Suggested proof: agentflight verify -- node -e");
    expect(markdown).toContain("…");
    expect(markdown).not.toContain("process.exit(1)");
  });

  it("keeps AgentLoopKit tooling diagnostics concise when doctor output is noisy", () => {
    const markdown = renderMarkdownReport({
      task: "Dogfood report",
      sessionId: "af-tooling",
      startedAt: "2026-06-17T12:00:00.000Z",
      changedFiles: ["README.md"],
      risk: {
        level: "low",
        changedFiles: 1,
        categories: [{ category: "docs", files: ["README.md"] }],
        reasons: ["Only low-risk docs, tests, or isolated UI files changed."]
      },
      verificationCommands: [],
      verificationEvidence: [],
      timelineEvents: [],
      tooling: {
        projscan: { available: true, warnings: [] },
        agentloopkit: {
          available: false,
          warnings: [
            "AgentLoopKit doctor reported issues: # AgentLoopKit Doctor\n\n- [`fail`] `agentloop.config.json`: `AgentLoopKit config not found at /repo/agentloop.config.json. Run agentloop init.`\n- [`warn`] `Template manifest`: `missing .agentloop/manifest.json`"
          ]
        }
      }
    });

    expect(markdown).toContain(
      "- AgentLoopKit: unavailable (AgentLoopKit doctor reported issues; run agentloopkit doctor for details.)"
    );
    expect(markdown).not.toContain("agentloop.config.json");
    expect(markdown).not.toContain("Template manifest");
  });

  it("renders a compact report without timeline or tooling sections", () => {
    const markdown = renderMarkdownReport(
      {
        task: "Failure review",
        sessionId: "af-compact",
        startedAt: "2026-06-17T12:00:00.000Z",
        changedFiles: ["src/api/users.ts"],
        risk: {
          level: "medium",
          changedFiles: 1,
          categories: [{ category: "backend/api", files: ["src/api/users.ts"] }],
          reasons: ["Backend/API files changed."]
        },
        verificationCommands: [],
        verificationEvidence: [
          {
            command: "npm test",
            startedAt: "2026-06-17T12:01:00.000Z",
            finishedAt: "2026-06-17T12:01:05.000Z",
            durationMs: 5000,
            exitCode: 1,
            status: "failed",
            stdoutPath: ".agentflight/evidence/af-compact/verification-1.stdout.txt",
            stderrPath: ".agentflight/evidence/af-compact/verification-1.stderr.txt",
            outputExcerpt: "expected failure excerpt"
          }
        ],
        timelineEvents: [],
        review: {
          focus: [
            {
              rank: 1,
              file: "src/api/users.ts",
              category: "backend/api",
              riskLevel: "medium",
              score: 100,
              reasons: ["backend/API file", "verification failed"],
              suggestedReviewerFocus: "Check request handling, validation, and error paths first.",
              proofStatus: "failed",
              suggestedCommand: "npm test",
              relatedProofGapIds: ["failed-verification"]
            }
          ],
          proofGaps: [
            {
              id: "failed-verification",
              severity: "blocking",
              message:
                "A verification command failed and must be fixed or rerun successfully: npm test",
              suggestedCommand: "npm test",
              relatedFiles: ["src/api/users.ts"]
            }
          ],
          readiness: {
            state: "blocked_by_failed_verification",
            label: "Blocked by failed verification",
            reason:
              "A verification command failed and must be fixed or rerun successfully: npm test",
            nextAction: "Fix the failed command, then rerun agentflight verify -- npm test",
            suggestedCommand: "npm test",
            proofGaps: []
          }
        },
        tooling: {
          projscan: { available: true, warnings: [] },
          agentloopkit: { available: true, warnings: [] }
        }
      },
      { mode: "compact" }
    );

    expect(markdown).toContain("# AgentFlight Compact Report");
    expect(markdown).toContain("## Review Readiness");
    expect(markdown).toContain("## Verification Evidence");
    expect(markdown).toContain("expected failure excerpt");
    expect(markdown).toContain(".agentflight/evidence/af-compact/verification-1.stderr.txt");
    expect(markdown).not.toContain("## Timeline");
    expect(markdown).not.toContain("## Tooling");
  });

  it("renders a local PR comment draft without posting-oriented claims", () => {
    const markdown = renderMarkdownReport(
      {
        task: "Review handoff",
        sessionId: "af-pr-comment",
        startedAt: "2026-06-17T12:00:00.000Z",
        changedFiles: ["src/api/users.ts"],
        risk: {
          level: "medium",
          changedFiles: 1,
          categories: [{ category: "backend/api", files: ["src/api/users.ts"] }],
          reasons: ["Backend/API files changed."]
        },
        verificationCommands: [],
        verificationEvidence: [
          {
            command: "npm test",
            startedAt: "2026-06-17T12:01:00.000Z",
            finishedAt: "2026-06-17T12:01:05.000Z",
            durationMs: 5000,
            exitCode: 0,
            status: "passed",
            stdoutPath: ".agentflight/evidence/af-pr-comment/verification-1.stdout.txt",
            stderrPath: ".agentflight/evidence/af-pr-comment/verification-1.stderr.txt"
          }
        ],
        timelineEvents: [],
        review: {
          focus: [
            {
              rank: 1,
              file: "src/api/users.ts",
              category: "backend/api",
              riskLevel: "medium",
              score: 70,
              reasons: ["backend/API file"],
              suggestedReviewerFocus: "Check request handling, validation, and error paths first.",
              proofStatus: "covered",
              relatedProofGapIds: []
            }
          ],
          proofGaps: [],
          readiness: {
            state: "ready_for_review",
            label: "Ready for review",
            reason: "Verification evidence matches the observed review risk.",
            nextAction:
              "Generate or share the AgentFlight report/replay and request scoped human review.",
            proofGaps: []
          }
        },
        tooling: {
          projscan: { available: true, warnings: [] },
          agentloopkit: { available: true, warnings: [] }
        }
      },
      { mode: "pr-comment" }
    );

    expect(markdown).toContain("## AgentFlight Review Summary");
    expect(markdown).toContain("Generated locally by AgentFlight. Not posted automatically.");
    expect(markdown).toContain("Readiness: Ready for review");
    expect(markdown).toContain("Review first");
    expect(markdown).toContain("src/api/users.ts");
    expect(markdown).toContain("Proof gaps: none");
    expect(markdown).toContain("npm test: passed");
    expect(markdown).toContain(".agentflight/evidence/af-pr-comment/verification-1.stdout.txt");
    expect(markdown).not.toContain("## Timeline");
    expect(markdown).not.toContain("## Tooling");
    expect(markdown).not.toContain("posted to GitHub");
  });
});
