import { describe, expect, it } from "vitest";
import { renderMarkdownReport } from "../../src/renderers/markdown-report.js";

describe("markdown proof report", () => {
  it("renders required sections without claiming missing proof passed", () => {
    const markdown = renderMarkdownReport({
      task: "Add password reset flow",
      sessionId: "af-1",
      startedAt: "2026-06-13T12:00:00.000Z",
      changedFiles: ["src/auth/reset.ts"],
      risk: {
        level: "high",
        changedFiles: 1,
        categories: [{ category: "auth", files: ["src/auth/reset.ts"] }],
        reasons: ["Authentication-sensitive files changed."]
      },
      verificationCommands: ["npm test"],
      verificationEvidence: [],
      timelineEvents: [],
      tooling: {
        projscan: { available: false, warnings: ["ProjScan unavailable"] },
        agentloopkit: { available: true, warnings: [] }
      }
    });

    expect(markdown).toContain("# AgentFlight Proof Report");
    expect(markdown).toContain("## Timeline");
    expect(markdown).toContain("No timeline events recorded.");
    expect(markdown).toContain("## Verification Evidence");
    expect(markdown).toContain("No verification evidence recorded.");
    expect(markdown).not.toContain("tests passed");
    expect(markdown).toContain("Generated by AgentFlight");
  });
});
