import { describe, expect, it } from "vitest";
import { renderMarkdownReport } from "../../src/renderers/markdown-report.js";

describe("markdown proof report", () => {
  it("renders required sections without claiming missing proof passed", () => {
    const markdown = renderMarkdownReport({
      task: "Add password reset flow",
      sessionId: "af-1",
      startedAt: "2026-06-13T12:00:00.000Z",
      changedFiles: ["src/auth/reset.ts"],
      risk: {
        level: "high",
        changedFiles: 1,
        categories: [{ category: "auth", files: ["src/auth/reset.ts"] }],
        reasons: ["Authentication-sensitive files changed."]
      },
      verificationCommands: ["npm test"],
      verificationEvidence: [],
      timelineEvents: [],
      review: {
        focus: [
          {
            rank: 1,
            file: "src/auth/reset.ts",
            category: "auth",
            riskLevel: "high",
            score: 130,
            reasons: ["identity/session path", "no passing test evidence"],
            suggestedReviewerFocus: "Check session, permission, and identity boundaries first.",
            proofStatus: "missing",
            suggestedCommand: "npm test",
            relatedProofGapIds: ["missing-auth-test-proof"]
          }
        ],
        proofGaps: [
          {
            id: "missing-auth-test-proof",
            severity: "blocking",
            message:
              "Sensitive auth, payment, or security files changed without passing test evidence.",
            suggestedCommand: "npm test",
            relatedFiles: ["src/auth/reset.ts"]
          }
        ],
        readiness: {
          state: "needs_verification",
          label: "Needs verification",
          reason:
            "Sensitive auth, payment, or security files changed without passing test evidence.",
          nextAction: "Run agentflight verify -- npm test",
          suggestedCommand: "npm test",
          proofGaps: []
        }
      },
      tooling: {
        projscan: { available: false, warnings: ["ProjScan unavailable"] },
        agentloopkit: { available: true, warnings: [] }
      }
    });

    expect(markdown).toContain("# AgentFlight Proof Report");
    expect(markdown).toContain("## Timeline");
    expect(markdown).toContain("No timeline events recorded.");
    expect(markdown).toContain("## Verification Evidence");
    expect(markdown).toContain("No verification evidence recorded.");
    expect(markdown).toContain("## Review First");
    expect(markdown).toContain("src/auth/reset.ts");
    expect(markdown).toContain("identity/session path");
    expect(markdown).toContain("## Proof Gaps");
    expect(markdown).toContain("Sensitive auth, payment, or security files changed");
    expect(markdown).toContain("## Review Readiness");
    expect(markdown).toContain("Needs verification");
    expect(markdown).not.toContain("tests passed");
    expect(markdown).toContain("Generated by AgentFlight");
  });
});
