import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { createTempRepo } from "../helpers/temp.js";
import { initAgentFlight } from "../../src/core/config.js";
import { startSession } from "../../src/core/session.js";
import { runReplayCommand } from "../../src/commands/replay.js";
import { runReportCommand } from "../../src/commands/report.js";
import { runResumeCommand } from "../../src/commands/resume.js";
import { runStatusCommand } from "../../src/commands/status.js";
import { runVerifyCommand } from "../../src/commands/verify.js";

describe("evidence-aware session outputs", () => {
  it("shows verification evidence and readiness in status", async () => {
    const command = `${process.execPath} -e "console.log('proof ok')"`;
    const repoRoot = await startedRepo([command]);
    await runVerifyCommand({
      repoRoot,
      commandArgs: [process.execPath, "-e", "console.log('proof ok')"],
      now: () => new Date("2026-06-13T12:00:00.000Z")
    });

    const status = await runStatusCommand({
      repoRoot,
      changedFiles: ["src/auth/reset.ts"],
      now: new Date("2026-06-13T12:05:00.000Z")
    });

    expect(status.output).toContain("Changed areas:");
    expect(status.output).toContain("- auth: src/auth/reset.ts");
    expect(status.output).toContain("Verification Evidence:");
    expect(status.output).toContain("1 passed, 0 failed");
    expect(status.output).toContain("Review readiness: Ready for review");
    expect(status.output).toContain("Proof missing:");
    expect(status.output).toContain("No configured verification gaps.");
  });

  it("marks failed verification as blocked in status", async () => {
    const repoRoot = await startedRepo([`${process.execPath} -e "process.exit(4)"`]);
    await runVerifyCommand({
      repoRoot,
      commandArgs: [process.execPath, "-e", "process.exit(4)"],
      now: () => new Date("2026-06-13T12:00:00.000Z")
    });

    const status = await runStatusCommand({
      repoRoot,
      changedFiles: ["src/auth/reset.ts"],
      now: new Date("2026-06-13T12:05:00.000Z")
    });

    expect(status.output).toContain("1 failed");
    expect(status.output).toContain("Review readiness: Blocked");
    expect(status.output).toContain("A verification command failed");
    expect(status.output).toContain("Fix the failed verification command");
  });

  it("includes verification evidence and recommendation in report and replay", async () => {
    const command = `${process.execPath} -e "console.log('proof ok')"`;
    const repoRoot = await startedRepo([command]);
    await runVerifyCommand({
      repoRoot,
      commandArgs: [process.execPath, "-e", "console.log('proof ok')"],
      now: () => new Date("2026-06-13T12:00:00.000Z")
    });

    const report = await runReportCommand({
      repoRoot,
      changedFiles: ["src/auth/reset.ts"]
    });
    const markdown = await readFile(report.reportPath, "utf8");
    expect(markdown).toContain("Ready for review");
    expect(markdown).toContain(command);
    expect(markdown).toContain(".agentflight/evidence/");
    expect(markdown).toContain("- auth: src/auth/reset.ts");

    const replay = await runReplayCommand({
      repoRoot,
      changedFiles: ["src/auth/reset.ts"]
    });
    const html = await readFile(replay.replayPath, "utf8");
    expect(html).toContain("verification-card");
    expect(html).toContain("passed");
    expect(html).toContain("Generated by AgentFlight");
    expect(html).not.toMatch(/https?:\/\//);
  });

  it("includes verification gaps and the exact next command in resume prompts", async () => {
    const repoRoot = await startedRepo(["npm test"]);

    const resume = await runResumeCommand({
      repoRoot,
      changedFiles: ["src/auth/reset.ts"]
    });

    expect(resume.output).toContain("Verification Gaps");
    expect(resume.output).toContain("npm test");
    expect(resume.output).toContain("Stay scoped to the current task.");
    expect(resume.output).toContain("Do not claim completion without proof.");
    expect(resume.output).toContain("Run relevant verification before declaring success.");
  });
});

async function startedRepo(verificationCommands: string[]): Promise<string> {
  const repoRoot = await createTempRepo();
  await initAgentFlight({ repoRoot, now: new Date("2026-06-13T11:00:00.000Z") });
  await startSession({
    repoRoot,
    task: "Capture verification",
    now: new Date("2026-06-13T11:30:00.000Z"),
    git: { branch: "main", commit: "abc123", dirty: false, changedFiles: [] },
    packageManager: "npm",
    verificationCommands,
    tools: {
      projscan: { available: true, warnings: [] },
      agentloopkit: { available: true, warnings: [] }
    }
  });
  return repoRoot;
}
